apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: rithwik504/basic-project:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: SECRET_KEY
              value: "supersecret"
