name: Django Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # Must be your local machine with Docker Desktop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest Docker image
        run: |
          docker pull rithwik504/basic-project:latest

      - name: Stop running container (if exists)
        run: |
          if docker ps -q -f name=basic-project; then
            docker stop basic-project
            docker rm basic-project
          fi

      - name: Run new container
        run: |
          docker run -d -p 8000:8000 --name basic-project rithwik504/basic-project:latest

      - name: Verify container is running
        run: docker ps
